version: '3'
services:
  cors-anywhere:
    image: testcab/cors-anywhere
    ports:
      - '8080:8080'
    restart: unless-stopped
  nginx:
    image: nginx
    ports:
      - '80:80'
    restart: unless-stopped
    volumes:
      - './wwwroot:/usr/share/nginx/html:ro'
