version: '3'
services:
  bot:
    build:
      context: .
    image: hxavatarsbot
    environment:
      AVATARS_FILE: /app/data/avatars.json
      CHOICES_FILE: /app/data/choices.json
    restart: unless-stopped
    volumes:
      - ./commands:/app/commands
      - ./configs:/app/configs
      - ./database.sqlite:/app/database.sqlite
      - ./shared:/app/data
      - ./mods:/app/mods
  cors:
    image: testcab/cors-anywhere
    restart: unless-stopped
  web:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./wwwroot:/usr/share/nginx/html/overlay
      - ./shared:/usr/share/nginx/html/data
