version: '3'
services:
  bot:
    build:
      context: .
    image: hxavatarsbot
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env
      - ./shared:/app/data
  web:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./wwwroot:/usr/share/nginx/html/overlay
      - ./shared:/usr/share/nginx/html/data
