version: '3'
services:
  bot:
    build:
      context: .
    command: /bin/sh -c "python3 -m hxavatars.web"
    image: hxavatarsbot
    ports:
      - 5000:5000
    restart: unless-stopped
    tty: true
    volumes:
      - ./.env:/app/.env
      - ./shared:/app/data
